FROM node:21.4.0

RUN apt update
RUN apt install git -y

RUN apt install nginx -y

WORKDIR /easyfish/frontend
ENV DOMAIN=localhost

# Downloads only package.json and install dependencies first
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm i
RUN rm package.json
RUN rm package-lock.json

# Clone just the "frontend" of github repo
LABEL random="0"
WORKDIR /easyfish
COPY . frontend

# Return to frontend folder
WORKDIR /easyfish/frontend

# Configure default envs
ENV API_ADDRESS=localhost
ENV API_PROTOCOL=http
ENV API_PORT=8080

ENV PRINTER_ADDRESS=localhost
ENV PRINTER_PROTOCOL=http
ENV PRINTER_PORT=8888  

# RUN rm /etc/nginx/conf.d/
RUN rm /etc/nginx/sites-enabled/*

# Configure the frontend entrypoint
RUN echo "node ./scripts/configureDockerContainer.mjs"     > start.sh && \
    echo "nginx -g 'daemon off;'"                          >> start.sh

RUN chmod +x start.sh

ENV PROD=true

CMD [ "./start.sh" ]
# CMD ["nginx", "-g", "daemon off;"]