const TRANSACTION_OPEN = 0
const TRANSACTION_INVALID = 1
const TRANSACTION_CLOSED = 2

export {TRANSACTION_INVALID,TRANSACTION_CLOSED,TRANSACTION_OPEN}
export default {TRANSACTION_INVALID,TRANSACTION_CLOSED,TRANSACTION_OPEN}