/**
 * Return only the "allowNull:true" attributes
 * @param {import("sequelize").ModelStatic<Model<any, any>>} table 
 * @returns {string[]}
 */

export function getOnlyNecessaryAttributes(table) {
    return Object.values(table.getAttributes()).filter((each) => {
        if (!each.allowNull &&
            !each.autoIncrement &&
            !each._autoGenerated &&
            each.defaultValue == undefined)
            return each
    }).map(each => each.field)
}

export function getReferenciedModels(table) {
    const attributes = Object.entries(table.getAttributes())

    const selected = attributes.filter(each => {
        if (each[1].references) {
            return each
        }
    }).map(each => each[1].references.model)

    return selected
}
